### ISSUE TITLE
Potential issue with "Predict" function 

### ISSUE THREAD

**Issue by JulianGaviriaL** [M-E-Rademaker/cSEM#437] opened 2021-07-10 15:32 UTC
I am trying use the Predict function:

```
#Running model:
model <- "

  # Composite variables
  X <~ Brain_prev1 + Brain_prev2
 Y <~ Brain_curr1 + Brain_curr2

           # direct effect
             Y ~ X
         "
res <- csem(.data=myDATA,.model=model, .resample_method = "bootstrap", .R=10000)
```

```
# Predict using 10-fold cross-validation with 5 repetitions 
## Not run: 
pp2 <- predict(res, .benchmark = "lm") 
```

Unfortunately it always yields the same error:

```
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('cSEMResults', 'cSEMResults_default')
```

I obtain the same output even with the example i found in the cSEM package documentation:

```
# Load data
data(Anime) 
# data is similar to the Anime.csv found on 
# https://github.com/ISS-Analytics/pls-predict but with irrelevant # columns removed
# Split into training and data the same way as it is done on
# https://github.com/ISS-Analytics/pls-predict set.seed(123)
index <- sample.int(dim(Anime)[1], 83, replace = FALSE) 
dat_train <- Anime[-index, ]
dat_test <- Anime[index, ]

# Specify model
model <- " # Structural model
ApproachAvoidance ~ PerceivedVisualComplexity + Arousal 

# Measurement/composite model 
ApproachAvoidance=~ AA0 + AA1 + AA2 + AA3
PerceivedVisualComplexity <~ VX0 + VX1 + VX2 + VX3 + VX4 
Arousal<~ Aro1 + Aro2 + Aro3 + Aro4 "

# Estimate (replicating the results of the ` simplePLS()` function) 
res <- csem(dat_train,
            model,
            .disattenuate = FALSE, # original PLS
            .iter_max = 300,
            .tolerance = 1e-07, 
            .PLS_weight_scheme_inner = "factorial"
)

# Predict using 10-fold cross-validation with 5 repetitions 
## Not run: 
pp2 <- predict(res, .benchmark = "lm") 
pp2 
```
```
Error in UseMethod("predict") : 
  no applicable method for 'predict' applied to an object of class "c('cSEMResults', 'cSEMResults_default')
```
Many thanks in advance for clarifying.

**Comment by M-E-Rademaker** [comment] 2021-07-10 16:47
You probably have another package loaded (AFTER you loaded cSEM) that also has a `predict()` function. Or you dont have cSEM loaded at all!?. This is something to be aware of when using R. 
To fix this, there are two ways:

1. Load cSEM **after** you load all other packages
2. Explicitly tell R to use `predict()` from cSEM by using the :: operator: `cSEM::predict(.object)`

**Comment by JulianGaviriaL** [comment] 2021-07-10 19:36
Thank you very much Manuel.
You were right. **The function works perfectly** after uninstalling further packages with the same function name. 

However, I wonder what the "dimension" issue means. I got it with my own data: 

```
library(readxl)
library(writexl)
library(cSEM)

myDATA<- read_excel("D:/I3/ana/CAP/metrics/SF/cSEM/data.xlsx", sheet = "input")

#Running model:
model <- "

  # Composite variables
  X <~ Brain_prev1 + Brain_prev2+ Brain_prev3
  Y <~ Brain_curr1 + Brain_curr2+ Brain_curr3
  
 # Structural model
   Y ~ X 
   "
pp2 <- predict(res2, .benchmark = "lm") 
```

```
Error in `colnames<-`(`*tmp*`, value = colnames(X_test)) : 
  attempt to set 'colnames' on an object with less than two dimensions
```

**Comment by M-E-Rademaker** [comment] 2021-07-10 19:47
What version of cSEM are you using? 0.4.0?

**Comment by JulianGaviriaL** [comment] 2021-07-10 19:56
```
> packageVersion('cSEM')
[1] ‘0.3.1’
```
I will try with 0.4.0 now

**Comment by JulianGaviriaL** [comment] 2021-07-10 20:26
same output with cSEM version 0.4.0

```
 > packageVersion('cSEM')
[1] ‘0.4.0’
> library(readxl)
> library(writexl)
> library(cSEM)
> myDATA<- read_excel("D:/I3/ana/CAP/metrics/SF/cSEM/data.xlsx", sheet = "input")
> 
> 
> 
> #Running model:
> model <- "
+ 
+   # Composite variables
+   X <~ Brain_prev1 + Brain_prev2+ Brain_prev3
+   Y <~ Brain_curr1 + Brain_curr2+ Brain_curr3
+   M <~ behavior1 + behavior2 + behavior3
+ 
+ 
+   
+  # Structural model
+    Y ~ X + M
+    "
> 
> res2 <- csem(myDATA,
+              model,
+              .disattenuate = FALSE, # original PLS
+              .iter_max = 300,
+              .tolerance = 1e-07, 
+              .PLS_weight_scheme_inner = "factorial"
+ )
> 
> 
> 
> pp2 <- predict(res2, .benchmark = "lm") 
```
```
[data.xlsx](https://github.com/M-E-Rademaker/cSEM/files/6795905/data.xlsx)
```

**Comment by M-E-Rademaker** [comment] 2021-07-10 21:05
Alright, I’ll have a look tomorrow. Can you post a reproducible example or provide (at least parts of) the data to me ?

**Comment by JulianGaviriaL** [comment] 2021-07-10 21:13
Please let me know in case you find problems to visualize the code below + the attached link for the data.
[data.xlsx](https://github.com/M-E-Rademaker/cSEM/files/6795950/data.xlsx)

```
library(readxl)
library(writexl)
library(cSEM)

#Running model:
model <- "

  # Composite variables
  X <~ Brain_prev1 + Brain_prev2+ Brain_prev3
  Y <~ Brain_curr1 + Brain_curr2+ Brain_curr3
  
 # Structural model
   Y ~ X 
   "
#I copied the cSEM components from your example:
res2 <- csem(myDATA,
             model,
             .disattenuate = FALSE, # original PLS
             .iter_max = 300,
             .tolerance = 1e-07, 
             .PLS_weight_scheme_inner = "factorial"
)

pp2 <- predict(res2, .benchmark = "lm") 
```

**Comment by M-E-Rademaker** [comment] 2021-07-11 11:15
Dear Julian,

this is indeed a bug that is due to a poor implementation of cross-validation on my side. Here is what happend:

### Issue

The issue occured because the `predict()` internally calls `resampleData()` to compute the cross-validation folds (which are necessary to compute the prediction metrics). Back then I implemented cross-validation myself (which I regret today, because it is not particualry fast and -- as you see -- I didnt not cover all edge cases that could possibly make things go wrong). 

In my implementation I (somewhat sloppily) split the data set such that each fold has `ceiling(nrow(data) / .cv_folds)` observations. In your case `nrow(data)` = 24, `.cv_folds` = 10 and therefore  `ceiling(nrow(data) / .cv_folds)`  = 3. Now, since
your data only has 24 rows but you requested 10 folds, the last two folds will have 0 observations (as 3*10 - 24 = 6 there are 6 observations "missing").

Using your data, you can check that yourself:

    resampleData(.data = myDATA, .resample_method = "cross-validation", .R = 1, .cv_folds = 10) # the last 2 folds are empty

The actual error you are seeing, is because within `predict()` colnames are set for each fold. But since the last two folds are actually empty, there are no column names to set.

### (Temporary) Fix

To fix this the quick and dirty way for now simply change the number of folds such that  `ceiling(nrow(data) / .cv_folds)` * `.cv_folds` <= `nrow(data)` or equal to `nrow(data)` (which is LOOCV). 

Once I get around, I'll fix my implementation to allow for unequal splits that ensure at least 1 observations per fold.

**Comment by JulianGaviriaL** [comment] 2021-07-15 13:29
Thank you Manuel.

Unfortunately decreasing the number of folds is not an option since it would yield spurious results. Following Shmueli et al., 2019, and  Kock2018, one should use leave one out cross-validation by setting k to 25.

**Comment by JulianGaviriaL** [comment] 2021-07-19 18:50
Thanks Manuel for clarifying. 

In order to apply your suggested temporary fix, what would be the right input line for the "predict" formula? 
myDATA<- read_excel("D:/I3/ana/CAP/metrics/SF/cSEM/data.xlsx", sheet = "input")

```
#Running model:
model <- "

# Composite variables
  X <~ Brain_prev1 + Brain_prev2+ Brain_prev3
  Y <~ Brain_curr1 + Brain_curr2+ Brain_curr3
  M <~ behavior1 + behavior2 + behavior3
  
 # Structural model
   Y ~ X + M
   "
res2 <- csem(myDATA,
             model,
             .disattenuate = FALSE, # original PLS
             .iter_max = 300,
             .tolerance = 1e-07, 
             .PLS_weight_scheme_inner = "factorial"
)

pp2 <- predict(res2, .benchmark = "lm", .cv_folds = nrow(myDATA))
```
Error in `colnames<-`(`*tmp*`, value = colnames(X_test)) : 
  attempt to set 'colnames' on an object with less than two dimensions

`pp2 <- predict(res2, .benchmark = "lm", .cv_folds = 24) #24=total number of observations`
Error in `colnames<-`(`*tmp*`, value = colnames(X_test)) : 
  attempt to set 'colnames' on an object with less than two dimensions

**Comment by M-E-Rademaker** [comment] 2021-07-19 20:15
Yes, indeed a bug. Fixed in the development version (0.4.0.9000)!

**Comment by JulianGaviriaL** [comment] 2021-07-20 09:46
Great!
It nicely worked out with the  version 0.4.0.9000. Thank a lot Manuel.

Just to report an additional detail (it's the least I can do in response to such an efficient support from your side!):
The plot function yielded error messages  with my data. I guess this is also related to the sample size, since I could plot the results with your example
https://m-e-rademaker.github.io/cSEM/reference/predict.html
and with this development version :

Trial including my own data:

```
devtools::install_github("M-E-Rademaker/cSEM")

#Running model:
model <- "

  # Composite variables
  X <~ Brain_prev1 + Brain_prev2+ Brain_prev3
  Y <~ Brain_curr1 + Brain_curr2+ Brain_curr3

 # Structural model
   Y ~ X
   "

res2 <- csem(myDATA,
             model,
             .disattenuate = FALSE, # original PLS
             .iter_max = 300,
             .tolerance = 1e-07, 
             .PLS_weight_scheme_inner = "factorial")

verify(res2)

pp2 <- predict(res2, .benchmark = "lm", .cv_folds = nrow(myDATA))
pp2 <- predict(res2, .benchmark = "lm", .cv_folds = 24)
plot(pp2)
```

________________________________________________________________________________
	Enter the number of the plot you want to show:

		1 - Actual values vs. predicted values
		2 - Estimated density function - residuals
		3 - Estimated density function - predicted values
________________________________________________________________________________
Your choice:1
Error in `[.data.frame`(xx, , "Predictions_target") : 
  undefined columns selected

Your choice:2
See attached image
![image](https://user-images.githubusercontent.com/51994999/126300041-7b8e99f3-06ce-4c66-be43-73800906f3fa.png)
 
Your choice:3
Error in `[.data.frame`(xx, , "Predictions_target") : 
  undefined columns selected

**Comment by M-E-Rademaker** [comment] 2021-07-20 09:50
Yes, I’ll have a look later today. But looks like it’s the same issue that caused the predict() function to fail. I’ll fix it and update.

**Comment by JulianGaviriaL** [comment] 2021-07-20 09:54
Thanks!

**Comment by JulianGaviriaL** [comment] 2021-07-20 17:08
Additionally, 

I wonder whether it is possible to obtain the values from the **endogenous constructs**, instead of the endogenous **constructs’ indicators**?. Such as it has been suggested in Hair et al., 2019. P 13).

Thanks in advance,

**Comment by M-E-Rademaker** [comment] 2021-07-22 13:02
https://github.com/M-E-Rademaker/cSEM/issues/437#issuecomment-883256338 is fixed.

**Comment by M-E-Rademaker** [comment] 2021-07-22 13:09
not directly, but you have estimated weights and predicted values for the indicators. The scores would simply be indicator scores * weights. So in your case:

```
X_predicted <- pp2$Predictions_target
W_estimated <- res2$Estimates$Weight_estimates

predicted_score_endo_construct <- X_predicted %*% t(W_estimated[2, 4:6, drop = FALSE])
```

**Comment by JulianGaviriaL** [comment] 2021-07-22 15:44
Dear @M-E-Rademaker,

I really appreciate your time you spend on fixing the bugs. Without your contribution, It would not be possible to run the analyses. Thank you so much!

**1. plotting predict output:**
The plot function perfectly worked out with my small sample size. 

**2. Obtaining values from "prediction" function for the endogenous constructs (not inicators)**
- Your suggested code also worked fine. Many thanks. I just adapted the matrix for cases when the constructs only have 2 indicators:

```
X_predicted <- pp2$Predictions_target
W_estimated <- res2$Estimates$Weight_estimates
predicted_score_endo_construct <- X_predicted %*% t(W_estimated[2, 3:4, drop = FALSE])

```
- I this context (i.e., prediction scores for constructs), I wonder whether it's possible to obtain an overview including the MAE, RMSE, and Q2 values, such as you nicely coded it for the constructs indicators?

```
________________________________________________________________________________
----------------------------------- Overview -----------------------------------

	Number of obs. training          = 23
	Number of obs. test              = 1
	Number of cv folds               = 24
	Number of repetitions            = 10
	Handle inadmissibles             = stop
	Target                           = 'PLS-PM'
	Benchmark                        = 'lm'

------------------------------ Prediction metrics ------------------------------


  Name            MAE target  MAE benchmark  RMSE target RMSE benchmark   Q2_predict
  Brain_curr1         4.9511         6.5057       6.2410         7.4651       0.3120
  Brain_curr2         3.7902         4.9458       4.6348         5.9589       0.4715
________________________________________________________________________________
```

**Comment by M-E-Rademaker** [comment] 2021-07-22 21:27
Thx for the kind words. MAE, RMSE etc. cannot be calculated like that, since they require cross-validation (which happens *inside* `predict()`). This would have to be implemented by e.g. adding a new argument which lets users choose whether to return construct or indicator scores. Please open a new issue with that feature request so it does not get lost.

**Comment by JulianGaviriaL** [comment] 2021-07-23 05:51
Perfect.  I will do it.
Many thanks @M-E-Rademaker.

**Closed** 2021-07-23 05:56 UTC
